[features]
seeds = false
skip-lint = false

[programs.localnet]
land = "puwD5S1FtQFqhxNTAq7EEjGzz3hoWnyNRHmx4wAZzTo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/db/.config/solana/id.json"

[test]
startup_wait = 5000

[test.validator]
url = "http://127.0.0.1:8989"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"