[features]
seeds = false
skip-lint = false
[programs.localnet]
citizenship = "FAASs3638wEGwWxhp8EkaDuU2ENV1r4c1nJPN9fHLGtp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/db/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
